server:
  port: 2000
  
eureka:
  client:
    service-url: http://eureka:8761/eureka
     defualtZone: http://eureka:8761/eurekafromconfigbranch


server.application.name=book-service-from-config-server
