server:
  port: 2000
  
eureka:
  client:
    service-url:
     defualtZone: http://eureka:8761/eurekafromconfigbranch
      



    

    

    
management:
  endpoints:
    web:
      exposure:
        include: info,beans,health,conditions,mappings,metrics,env,threaddump,httptrace
  endpoint:
    health:
      show-details: always



spring:
  application:
    name: book-service-config

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  
