server:
  port: 8072
  

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    
spring:
  cloud:
    gateway:
      routes:
      - id: book-service
        uri: lb://book-service
        predicates:
        - path=/books/**
        filters:
        - RewritePath=/books/(?<path>.*),/$\{path}
      discovery.locator:
        enabled: true
        lowerCaseSErviceId: true
        
        
        
        
        
management:
  endpoints:
    web:
      exposure:
        include: "*"        

#    service-url: http://eurekaserver:8761/eureka/  
